/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#include <osmocom/rspro/SlotPhysStatus.h>

static asn_TYPE_member_t asn_MBR_SlotPhysStatus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SlotPhysStatus, resetActive),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resetActive"
		},
	{ ATF_POINTER, 3, offsetof(struct SlotPhysStatus, vccPresent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vccPresent"
		},
	{ ATF_POINTER, 2, offsetof(struct SlotPhysStatus, clkActive),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"clkActive"
		},
	{ ATF_POINTER, 1, offsetof(struct SlotPhysStatus, cardPresent),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cardPresent"
		},
};
static const ber_tlv_tag_t asn_DEF_SlotPhysStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SlotPhysStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* resetActive */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vccPresent */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* clkActive */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* cardPresent */
};
static asn_SEQUENCE_specifics_t asn_SPC_SlotPhysStatus_specs_1 = {
	sizeof(struct SlotPhysStatus),
	offsetof(struct SlotPhysStatus, _asn_ctx),
	asn_MAP_SlotPhysStatus_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SlotPhysStatus = {
	"SlotPhysStatus",
	"SlotPhysStatus",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No UPER support, use "-gen-PER" to enable */
	0, 0,	/* No APER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SlotPhysStatus_tags_1,
	sizeof(asn_DEF_SlotPhysStatus_tags_1)
		/sizeof(asn_DEF_SlotPhysStatus_tags_1[0]), /* 1 */
	asn_DEF_SlotPhysStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_SlotPhysStatus_tags_1)
		/sizeof(asn_DEF_SlotPhysStatus_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SlotPhysStatus_1,
	4,	/* Elements count */
	&asn_SPC_SlotPhysStatus_specs_1	/* Additional specs */
};

