/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_ConfigClientBankReq_H_
#define	_ConfigClientBankReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/BankSlot.h>
#include <osmocom/rspro/IpPort.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfigClientBankReq */
typedef struct ConfigClientBankReq {
	BankSlot_t	 bankSlot;
	IpPort_t	 bankd;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfigClientBankReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfigClientBankReq;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfigClientBankReq_H_ */
#include <asn_internal.h>
