/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_ConfigClientReq_H_
#define	_ConfigClientReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ClientSlot.h>
#include <osmocom/rspro/IpPort.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfigClientReq */
typedef struct ConfigClientReq {
	ClientSlot_t	 clientSlot;
	IpPort_t	 bankd;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfigClientReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfigClientReq;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfigClientReq_H_ */
#include <asn_internal.h>
