/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_ConnectClientReq_H_
#define	_ConnectClientReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ComponentIdentity.h>
#include <osmocom/rspro/ClientId.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConnectClientReq */
typedef struct ConnectClientReq {
	ComponentIdentity_t	 identity;
	ClientId_t	*clientId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectClientReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectClientReq;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectClientReq_H_ */
#include <asn_internal.h>
