/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_ConnectBankReq_H_
#define	_ConnectBankReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ComponentIdentity.h>
#include <osmocom/rspro/BankId.h>
#include <osmocom/rspro/SlotNumber.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConnectBankReq */
typedef struct ConnectBankReq {
	ComponentIdentity_t	 identity;
	BankId_t	 bankId;
	SlotNumber_t	 numberOfSlots;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectBankReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectBankReq;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectBankReq_H_ */
#include <asn_internal.h>
