/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_CreateMappingReq_H_
#define	_CreateMappingReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ClientSlot.h>
#include <osmocom/rspro/BankSlot.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateMappingReq */
typedef struct CreateMappingReq {
	ClientSlot_t	 client;
	BankSlot_t	 bank;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateMappingReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateMappingReq;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateMappingReq_H_ */
#include <asn_internal.h>
