/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_CreateMappingRes_H_
#define	_CreateMappingRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ResultCode.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateMappingRes */
typedef struct CreateMappingRes {
	ResultCode_t	 result;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateMappingRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateMappingRes;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateMappingRes_H_ */
#include <asn_internal.h>
