/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_ResetStateReq_H_
#define	_ResetStateReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResetStateReq */
typedef struct ResetStateReq {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResetStateReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResetStateReq;

#ifdef __cplusplus
}
#endif

#endif	/* _ResetStateReq_H_ */
#include <asn_internal.h>
