/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_RsproPDU_H_
#define	_RsproPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <osmocom/rspro/OperationTag.h>
#include <osmocom/rspro/RsproPDUchoice.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RsproPDU */
typedef struct RsproPDU {
	long	 version;
	OperationTag_t	 tag;
	RsproPDUchoice_t	 msg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RsproPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RsproPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _RsproPDU_H_ */
#include <asn_internal.h>
