/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPRO"
 * 	found in "../../asn1/RSPRO.asn"
 */

#ifndef	_TpduModemToCard_H_
#define	_TpduModemToCard_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/rspro/ClientSlot.h>
#include <osmocom/rspro/BankSlot.h>
#include <osmocom/rspro/TpduFlags.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TpduModemToCard */
typedef struct TpduModemToCard {
	ClientSlot_t	 fromClientSlot;
	BankSlot_t	 toBankSlot;
	TpduFlags_t	 flags;
	OCTET_STRING_t	 data;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TpduModemToCard_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TpduModemToCard;

#ifdef __cplusplus
}
#endif

#endif	/* _TpduModemToCard_H_ */
#include <asn_internal.h>
